pipeline {
    agent any
    tools {
        maven 'apache maven 3.6.3'
        jdk 'JDK 11'
    }
    stages {
        stage('Clean') {
            steps {
                sh 'mvn -f ./JenkinsCalculator/pom.xml clean'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -f ./JenkinsCalculator/pom.xml compile'
            }
        }
        stage('Short Tests') {
            steps {
                sh 'mvn -f ./JenkinsCalculator/pom.xml -Dtest=CalculatorTest test'
            }
        }
        stage('Long Tests') {
            steps {
                sh 'mvn -f ./JenkinsCalculator/pom.xml -Dtest=CalculatorTestThorough test'
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml'
                }
            }
        }
        stage('Package') {
            steps {
                sh 'mvn -f ./JenkinsCalculator/pom.xml package'
                archiveArtifacts artifacts: 'src/**/*.java'
                archiveArtifacts artifacts: 'target/*.jar'
            }
        }
    }
    }
